import Navbar from "@/components/Navbar";
import Head from "next/head";
// import Swiper core and required modules
import { Navigation, Pagination, Scrollbar, A11y } from "swiper";

import { Swiper, SwiperSlide } from "swiper/react";

// Import Swiper styles
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

import { IoMail } from "react-icons/io5";
import { BsGithub, BsInstagram, BsFacebook } from "react-icons/bs";
import { useEffect, useRef } from "react";

export default function Home() {
  const articles = [
    {
      img: "article1.png",
      date: "10 Dec 2022",
      title: "APEC2022: ความหวังใหม่ทางเศรษฐกิจ หรือ ฟอกเขียวทุนเดิม",
      tag: ["APEC2022", "ฟอกเขียวทุนเดิม"],
    },
    {
      img: "article2.png",
      date: "7 Dec 2022",
      title: "สรุปงานเสวนา On the Margin of COP27Voicing the Critical Outside",
      tag: ["COP27"],
    },
    {
      img: "article3.png",
      date: "22 Nov 2022",
      title: "COP27: No time to waste or Waste of time?",
      tag: ["COP27"],
    },
  ];
  return (
    <>
      <Head>
        <title>CHULA POLITICS LAB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <Navbar />
      <main className="container mx-auto px-10 py-20">
        <img src="/img/logo.png" className="mx-auto w-32" alt="" />
        <h1 className="mb-10 mt-4 text-center text-6xl font-extrabold text-gray-800">
          CHULA <br className=" md:hidden" />
          <span className="text-[#dd757c]">POLITICS LAB</span>
        </h1>
        <p className="mx-auto max-w-5xl text-center text-xl text-gray-800">
          Lorem Ipsum is simply dummy text of the printing and typesetting
          industry. Lorem Ipsum has been the industry&lsquo;s standard dummy
          text ever since the 1500st when an unknown printer took a galley of
          type and scrambled it to make a type specimen book.
        </p>
        <div className="mt-20 grid grid-cols-2 gap-10 sm:grid-cols-3 lg:grid-cols-6">
          <div className="seal h-96 w-full translate-y-20 bg-[#ebb6be] lg:h-[600px] "></div>
          <div className="seal h-96 w-full bg-[#ebb6be] lg:h-[600px]"></div>
          <div className="seal h-96 w-full translate-y-20 bg-[#ebb6be] lg:h-[600px] lg:translate-y-36"></div>
          <div className="seal h-96 w-full bg-[#ebb6be] sm:translate-y-20 lg:h-[600px] lg:translate-y-36"></div>
          <div className="seal h-96 w-full translate-y-20 bg-[#ebb6be] sm:translate-y-0 lg:h-[600px]"></div>
          <div className="seal h-96 w-full bg-[#ebb6be] sm:translate-y-20 lg:h-[600px]"></div>
        </div>
      </main>
      <div className="container mx-auto grid px-10 py-48 lg:grid-cols-2">
        <div className="flex items-center justify-center">
          <div>
            <h1 className="py-8 text-4xl font-extrabold text-[#dd757c]">
              WHAT WE DO
            </h1>
            <p className=" max-w-2xl text-xl text-gray-800">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry. Lorem Ipsum has been the industry&lsquo;s standard dummy
              text ever Since the 1500s, when an unknown printer took a galley
              of type and scrambled it to make a type specimen book.
            </p>
          </div>
        </div>
        <Swiper
          // install Swiper modules
          modules={[Navigation, Pagination, Scrollbar, A11y]}
          spaceBetween={50}
          slidesPerView={1}
          navigation
          onSwiper={(swiper) => console.log(swiper)}
          onSlideChange={() => console.log("slide change")}
          className="w-full"
        >
          <SwiperSlide>
            <img
              src="https://content.phuket101.net/wp-content/uploads/20191014210458/monkeys-hill-phuket-1.jpg"
              className="w-full"
              alt=""
            />
          </SwiperSlide>
          <SwiperSlide>
            <img
              src="https://content.phuket101.net/wp-content/uploads/20191014210458/monkeys-hill-phuket-1.jpg"
              className="w-full"
              alt=""
            />
          </SwiperSlide>
        </Swiper>
      </div>

      <div className="container mx-auto mb-1">
        <p className="inline rounded-tl-xl bg-[#d66374] px-3 py-1 text-xl font-extrabold text-white ">
          EXPLORE OUR LABS
        </p>
        <p className="inline cursor-pointer rounded-tr-xl bg-[#2d262d] px-3 py-1 text-xl font-extrabold text-white">
          CLICK !
        </p>
      </div>

      <Swiper
        // install Swiper modules
        modules={[Navigation, Pagination, Scrollbar, A11y]}
        spaceBetween={50}
        slidesPerView={1}
        navigation
        onSwiper={(swiper) => console.log(swiper)}
        onSlideChange={() => console.log("slide change")}
        className="w-full"
      >
        <SwiperSlide>
          <img src="./img/explore.jpg" className="w-full" alt="" />
        </SwiperSlide>
        <SwiperSlide>
          <img src="./img/explore.jpg" className="w-full" alt="" />
        </SwiperSlide>
      </Swiper>

      <div className="container mx-auto px-10 pb-52 pt-32">
        <h1 className="py-8 text-4xl font-extrabold text-[#dd757c]">
          PROJECTS
        </h1>
        <div className="grid gap-28 sm:grid-cols-2 lg:grid-cols-3">
          <div className="w-full">
            <img src="./img/color_logo.png" className="w-full" alt="" />
            <p className="mt-7 text-xl font-bold text-gray-800 ">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry
            </p>
          </div>
          <div className="w-full">
            <img src="./img/color_logo.png" className="w-full" alt="" />
            <p className="mt-7 text-xl font-bold text-gray-800 ">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry
            </p>
          </div>
          <div className="w-full">
            <img src="./img/color_logo.png" className="w-full" alt="" />
            <p className="mt-7 text-xl font-bold text-gray-800 ">
              Lorem Ipsum is simply dummy text of the printing and typesetting
              industry
            </p>
          </div>
        </div>
      </div>
      <p className="inline bg-[#2d262d] px-20 py-3 text-3xl font-extrabold text-white ">
        ARTICLES
      </p>
      <div className="bg-[#2d262d] py-28 text-white">
        <div className="container mx-auto px-10">
          {articles.length > 0 ? (
            <Swiper
              // install Swiper modules
              modules={[Navigation, Pagination, Scrollbar, A11y]}
              className="article"
              spaceBetween={50}
              slidesPerView={1}
              navigation
              onSwiper={(swiper) => console.log(swiper)}
              onSlideChange={() => console.log("slide change")}
              breakpoints={{
                // when window width is >= 640px
                640: {
                  slidesPerView: 2,
                },
                // when window width is >= 768px
                1024: {
                  slidesPerView: 3,
                },
              }}
            >
              {articles.map((item, idx) => (
                <SwiperSlide key={idx}>
                  <img src={`./img/${item.img}`} className="w-full" alt="" />
                  <p className="mt-7">{item.date}</p>
                  <h1 className="my-3 text-xl font-bold leading-relaxed">
                    {item.title}
                  </h1>
                  {item.tag.map((tag, idx) => (
                    <p
                      key={idx}
                      className="mr-3 inline-block bg-[#d76275] px-5 py-2 font-bold"
                    >
                      {tag}
                    </p>
                  ))}
                </SwiperSlide>
              ))}
            </Swiper>
          ) : null}
        </div>
      </div>
      <div className="container mx-auto max-w-7xl px-10 py-32">
        <h1 className="pb-8 text-4xl font-extrabold text-[#dd757c]">
          PO LAB&rsquo;S NEWS
        </h1>
        <div className="gap-36 border-y border-slate-300 py-7 lg:flex">
          <p className=" text-xl font-extrabold text-gray-800">14.12.2022</p>
          <p className=" text-xl font-bold text-gray-700">
            Lorem Ipsum has been the industry&lsquo;s standard dummy text ever
            since the 1500s
          </p>
        </div>
        <div className="gap-36 border-y border-slate-300 py-7 lg:flex">
          <p className=" text-xl font-extrabold text-gray-800">14.12.2022</p>
          <p className=" text-xl font-bold text-gray-700">
            Lorem Ipsum has been the industry&lsquo;s standard dummy text ever
            since the 1500s
          </p>
        </div>
        <div className="gap-36 border-y border-slate-300 py-7 lg:flex">
          <p className=" text-xl font-extrabold text-gray-800">14.12.2022</p>
          <p className=" text-xl font-bold text-gray-700">
            Lorem Ipsum has been the industry&lsquo;s standard dummy text ever
            since the 1500s
          </p>
        </div>
      </div>

      <div className=" bg-gradient-to-br from-[#f19797] to-[#fac697] px-10 py-32">
        <div className="mx-auto max-w-5xl text-center">
          <h1 className="pb-8 text-center text-4xl font-extrabold text-white">
            EXPLORE YOUR TOPICS
          </h1>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl  font-bold text-white">
            APEC2022
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            ฟอกเขียวทุนเดิม
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            COP27
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            APEC2022
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            ฟอกเขียวทุนเดิม
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            COP27
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            APEC2022
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            ฟอกเขียวทุนเดิม
          </p>
          <p className="mx-2 mt-4 inline-block bg-[#d76275] px-7 py-3 text-xl font-bold text-white">
            COP27
          </p>
        </div>
      </div>

      <div className="container mx-auto max-w-7xl px-5 py-32 text-center">
        <h1 className="pb-8 text-center text-4xl font-extrabold text-[#dd757c]">
          OUR PARTNERSHIP
        </h1>
        <a className="opacity-60 grayscale duration-150 ease-in-out hover:opacity-100 hover:grayscale-0 ">
          <img
            src="./img/chula_logo.png"
            className="mx-auto my-7 inline w-3/4 px-8 py-5 sm:w-2/6 md:w-2/6 md:px-8 lg:w-1/4 lg:py-8"
            alt=""
          />
        </a>
        <a className="opacity-60 grayscale duration-150 ease-in-out hover:opacity-100 hover:grayscale-0">
          <img
            src="./img/chula_logo.png"
            className="mx-auto my-7 inline w-3/4 px-8 py-5 sm:w-2/6 md:w-2/6 md:px-8 lg:w-1/4 lg:py-8 "
            alt=""
          />
        </a>
        <a className="opacity-60 grayscale duration-150 ease-in-out hover:opacity-100 hover:grayscale-0">
          <img
            src="./img/chula_logo.png"
            className="mx-auto my-7 inline w-3/4 px-8 py-5 sm:w-2/6 md:w-2/6 md:px-8 lg:w-1/4 lg:py-8 "
            alt=""
          />
        </a>
        <a className="opacity-60 grayscale duration-150 ease-in-out hover:opacity-100 hover:grayscale-0">
          <img
            src="./img/chula_logo.png"
            className="mx-auto my-7 inline w-3/4 px-8 py-5 sm:w-2/6 md:w-2/6 md:px-8 lg:w-1/4 lg:py-8 "
            alt=""
          />
        </a>
        <a className="opacity-60 grayscale duration-150 ease-in-out hover:opacity-100 hover:grayscale-0">
          <img
            src="./img/chula_logo.png"
            className="mx-auto my-7 inline w-3/4 px-8 py-5 sm:w-2/6 md:w-2/6 md:px-8 lg:w-1/4 lg:py-8 "
            alt=""
          />
        </a>
        <a className="opacity-60 grayscale duration-150 ease-in-out hover:opacity-100 hover:grayscale-0">
          <img
            src="./img/chula_logo.png"
            className="mx-auto my-7 inline w-3/4 px-8 py-5 sm:w-2/6 md:w-2/6 md:px-8 lg:w-1/4 lg:py-8 "
            alt=""
          />
        </a>
        <a className="opacity-60 grayscale duration-150 ease-in-out hover:opacity-100 hover:grayscale-0">
          <img
            src="./img/chula_logo.png"
            className="mx-auto my-7 inline w-3/4 px-8 py-5 sm:w-2/6 md:w-2/6 md:px-8 lg:w-1/4 lg:py-8 "
            alt=""
          />
        </a>
      </div>

      <div className="bg-[#f0f0f0] py-28 text-gray-800 ">
        <div className="container mx-auto grid gap-36 px-10 md:grid-cols-2 xl:grid-cols-3">
          <div>
            <h1 className="mb-5  text-2xl font-extrabold">
              CHULA POLITICS LAB
            </h1>
            <p className="my-1 text-xl">Articles</p>
            <p className="my-1 text-xl">Data viz/stories</p>
            <p className="my-1 text-xl">Projects</p>
            <h1 className="mb-2 mt-10 text-xl font-extrabold">
              LAB นโยบายมานุษยวิทยา
            </h1>
            <h1 className="mb-2  text-xl font-extrabold">
              LAB นโยบายระดับมหาวิทยาลัย
            </h1>
            <h1 className="mb-2  text-xl font-extrabold">
              LAB นโยบายการศึกษา
            </h1>
            <h1 className="mb-2  text-xl font-extrabold">
              LAB นโยบายการเมืองและกฏหมาย
            </h1>
            <h1 className="mb-2  text-xl font-extrabold">
              LAB นโยบายสิ่งแวดล้อมและสาธารณภัย
            </h1>
          </div>
          <div>
            <h1 className="mb-2 text-2xl font-extrabold">ABOUT</h1>
            <h1 className="mb-5 text-2xl font-extrabold">
              ABOUT CHULA POLITICS LAB
            </h1>
            <p className="my-1 text-xl">Background</p>
            <p className="my-1 text-xl">Vision</p>
            <p className="my-1 text-xl">Labs</p>
            <p className="my-1 text-xl">Partnership</p>
            <br />
            <br />
            <p className="my-1 text-xl">News</p>
            <p className="my-1 text-xl">Recruitment</p>
            <p className="my-1 text-xl">E-Service</p>
          </div>
          <div>
            <h1 className="mb-2 text-2xl font-extrabold">CONTACT</h1>
            <h1 className="mb-2 text-xl font-bold">CHULA POLITICS LAB</h1>
            <h1 className="mb-5 text-xl font-bold">
              Chulalongkorn University
            </h1>
            <br />
            <p className="my-1 max-w-sm text-xl">
              Phayathai Road, Pathumwan, Bangkok 10330 Thailand
            </p>
            <br />
            <p className="my-1 text-xl font-bold">
              <IoMail className="inline text-2xl" />
              &nbsp; thecupolitics.lab@gmail.com
            </p>
          </div>
        </div>
      </div>
      <div className="flex items-center justify-between px-10">
        <img src="./img/logo.png" className="w-14" alt="" />
        <p className="text-lg font-bold text-gray-600">
          Follow us &nbsp;&nbsp;
          <BsFacebook className="mx-2 inline text-xl" />
          <BsInstagram className="mx-2 inline text-xl" />
          <BsGithub className="mx-2 inline text-xl" />
        </p>
      </div>
    </>
  );
}
